### ISSUE TITLE
why do i cant change the port in webserver like i need to do it with env

### ISSUE THREAD

**Issue by achiragaming** [iv-org/youtube-trusted-session-generator#19]
this is my compose 
```
version: '3'

services:
  youtube-trusted-session:
    image: quay.io/invidious/youtube-trusted-session-generator:webserver
    environment:
      - PORT=8560
      - HOST=0.0.0.0
    ports:
      - "8080:8560"
    restart: unless-stopped
```

but the logs say this 
```
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
2024/11/25 07:06:19.462 [extractor] [INFO] update started
2024/11/25 07:06:22.385 [extractor] [INFO] new token: {"updated": 1732518382, "potoken": "***", "visitor_data": "***"}
2024/11/25 07:06:22.386 [extractor] [INFO] update was succeessful
2024/11/25 07:06:22.387 [extractor] [INFO] update started
2024/11/25 07:06:22.388 [server] [INFO] Starting web-server at 0.0.0.0:8080
2024/11/25 07:06:23.488 [extractor] [INFO] new token: {"updated": 1732518383, "potoken": "***", "visitor_data": "***"}
2024/11/25 07:06:23.490 [extractor] [INFO] update was succeessful```
