### ISSUE TITLE
Webserver: High memory usage (Possible memory leak?)

### ISSUE THREAD

**Issue by LabodiDavid** [iv-org/youtube-trusted-session-generator#34]
I'm using the `quay.io/invidious/youtube-trusted-session-generator:webserver` docker image on a Debian 12 host.
After a 14 day uptime, the docker image is using about 3GB of RAM.

Here is the `top` command output from the container:

![Image](https://github.com/user-attachments/assets/9776ddff-3199-4626-a658-c6fab87882f8)

I have managed to limit the container's RAM to prevent usages like this.

My current docker-compose configuration:

```yaml
version: "3.2"
services:
  yt-trusted-session-generator:
    container_name: youtube-trusted-session-generator
    image: quay.io/invidious/youtube-trusted-session-generator:webserver
    network_mode: "bridge"
    ports:
      - 2334:8080
    mem_limit: 512m
```
